import './globals.css'
import { Inter } from 'next/font/google'
import SideBar from "@/components/SideBar";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Examen 01',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <SideBar />
      <div className="w-full md:w-[calc(100%-256px)] ml-64 bg-gray-50 min-h-screen transition-all">
        {children}
        </div>
</body>
    </html>
  )
}
